# Importações


In [2]:
import numpy as np
import numpy.ma as ma
import cv2
from google.colab.patches import cv2_imshow
import statistics

# 1) Como mudar os itens do array?

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = []
arr = np.where(arr % 2 == 1, arr, 0) 
arr = np.where (arr % 2 == 0, arr, 1)

for i in arr:
    if i == 0:
        i += 1
    if i == 1:
        i += 10
    arr2.append(i)
print(arr)
print(arr2)

[0 1 0 1 0 1 0 1 0 1]
[11, 11, 11, 11, 11, 11, 11, 11, 11, 11]


# 2) Como empilhar dois arrays verticalmente?

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

ab = np.concatenate((a,b), axis=0)
ab

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 3) Como empilhar dois arrays horizontalmente?

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

ab = np.concatenate((a,b), axis=1)
ab

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

4) Como criar a seguinte sequência com numpy.

In [16]:
from numpy.lib.shape_base import array_split
a = np.array([1, 2, 3])

a = np.hstack((np.repeat(a,3), np.tile(a,3)))

a

# Resposta obtida a partir da logica do colega Marcus Faustino 

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

5) Como pegar os elementos em comum entre dois arrays?


In [20]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

ab = np.intersect1d(a, b)
ab

array([2, 4])

6) Como pegar as posições de elementos iguais entre dois arrays?
Entrada:

In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

ab = np.where(a == b)
ab

(array([1, 3, 5, 7]),)

7) Como extrair todos os números em um intervalo desejado?
Entrada:

In [38]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

b = a[(a>=6)*(a<=10)]

b

array([ 6,  9, 10])

8) Como transformar um array 2D em um array 1D, crie um array 2D com uma
quantidade arbitrária de linhas e colunas e transforme em um array 1D.

In [46]:
arr_2d = np.random.randint(1,10,(2,4))

arr_1d = arr_2d.flatten()

print(arr_2d)

arr_1d

[[6 7 5 2]
 [7 2 3 8]]


array([6, 7, 5, 2, 7, 2, 3, 8])

9) Crie uma ufunc para transformar uma imagem colorida em uma imagem em
escala de cinza e aplique em um programa.

[[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]]


10) O seguinte link contém imagens comparativas dos registros dos telescópios
Hubble e James Webb de diferentes partes do cosmos. Faça o download das
imagens de um dos registros escolhidos, carregue a imagem com o opencv, e
realize os seguintes processamentos.


a) Crie e aplique filtros para exibir as imagens em cores vermelho, verde
e azul separadamente, para que possamos observar esses espectros
da luz visível separadamente.

b) Crie e aplique um filtro que procure exibir somente (ou quase isso) os
pontos mais brilhantes da imagem (normalmente estrelas ou galáxias)